---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: confluentplatforms.kafka.pm.bet
spec:
  group: kafka.pm.bet
  names:
    kind: ConfluentPlatform
    listKind: ConfluentPlatformList
    plural: confluentplatforms
    singular: confluentplatform
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1beta1
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: topics.kafka.pm.bet
spec:
  group: kafka.pm.bet
  names:
    kind: Topic
    listKind: TopicList
    plural: topics
    singular: topic
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1beta1
    served: true
    storage: true

