apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: confluentplatforms.pm.bet
spec:
  group: pm.bet
  names:
    kind: ConfluentPlatform
    listKind: ConfluentPlatformList
    plural: confluentplatforms
    singular: confluentplatform
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
