---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: confluent-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      name: confluent-platform
  template:
    metadata:
      labels:
        name: confluent-platform
    spec:
      serviceAccountName: confluent-platform
      containers:
        - name: confluent-platform
          # Replace this with the built image name
          image: "git.betlab.com:4567/kubernetes/operators/confluent-platform:v0.0.2"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "confluent-platform"
            - name: ANSIBLE_GATHERING
              value: explicit
      imagePullSecrets:
      - name: deploy-secret
      volumes:
        - name: runner
          emptyDir: {}
